### PR TITLE
modify the search box and search result design

### PR DESCRIPTION
**Pull request by AemieJ**
* I have modified the search box design and implemented a neat standard design for the search box.
* For the search result box, the box-shadow was redundant. Hence, I modified the box-shadow value so it looks adequate in reference to the background.

### BEFORE SEARCH-BOX DESIGN 
search-box-before

### AFTER SEARCH-BOX DESIGN
search-box-after

### CODE REVIEW

**Comment by aashnajena** [comment]
Hey, I'm already working on the search results design, there's already a PR for it. Please try not to make any conflicting changes (eg. changing the box-shadow attribute). Any suggestions you might have about it, you can comment on #317 and I will incorporate it with my ideas. Thanks!

**Comment by AemieJ** [comment]
I know you have made a PR regarding the search result design. I made one to encompass the whole design and our suggestions to the changes are different.

**Comment by zregvart** [comment]
@AemieJ does it make sense to rebase this and incorporate the changes on top of what we currently have?

**Comment by AemieJ** [comment]
> @AemieJ does it make sense to rebase this and incorporate the changes on top of what we currently have?

Yes, because this design is neat in my opinion and reduces the box shadow for the search result box as well. I have taken this design into account with respect to other website designs.

**Comment by zregvart** [comment]
Thanks!

**Pull request merged**
