### PR TITLE
CAMEL-14772: showcase Camel projects

### PR DESCRIPTION
**Pull request by zregvart**
This cleans up #270 to add section with Camel projects to frontpage. Responsive design is a bit rudimentary.

Wide:

Screenshot_2020-04-07 Home - Apache Camel

1024px:

Screenshot_2020-04-07 Home - Apache Camel(1)

625px:

Screenshot_2020-04-07 Home - Apache Camel(2)

### CODE REVIEW

**Comment by oscerd** [comment]
LGTM.

**Comment by davsclaus** [comment]
LGTM.

**Comment by zregvart** [comment]
Thanks @jyotiattri for kick-starting this effort!

**Comment by jyotiattri** [comment]
It's my pleasure @zregvart , Thanks a lot for your guidance and support.

**Pull request merged**
