### PR TITLE
chore(blog): camel k 1.5 new configuration explained

### PR DESCRIPTION
**Pull request by squakez**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by squakez** [comment]
Apparently this blog was not yet published. Is there any issue we should fix? @oscerd @zregvart do you have any idea why it's not yet there? Thanks.

**Comment by oscerd** [comment]
Broken build https://ci-builds.apache.org/job/Camel/job/Camel.website/job/main/288/console

**Comment by zregvart** [comment]
Wonder why those checks didn't fail on GitHub Actions, should be the same as on Jenkins for publishing.

**Comment by squakez** [comment]
> Wonder why those checks didn't fail on GitHub Actions, should be the same as on Jenkins for publishing.

Yes, I remind they failed in other occasions.

**Comment by squakez** [comment]
I've patched the failing links, however I am not able to spot those "Trailing whitespace" complains. Are those treated as warnings by any chance? Running the checks locally I see many of those in many pages.

**Comment by zregvart** [comment]
Aaah, the blog had a publish date in the future, and it wasn't built so checks had nothing to check.

**Comment by squakez** [comment]
Good to know for next writings!

**Pull request merged**
