### PR TITLE
blog: Outreachy May 2022 Participation

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by astefanutti** [comment]
@oscerd, the build fails with the following error:

```
YN0000: [build:antora  ] [build:antora-perf] [17ː29ː44.902] ERROR (asciidoctor): target of xref not found: 3.15.x@components::google-secret-manager-component.adoc
YN0000: [build:antora  ] [build:antora-perf]     file: docs/modules/ROOT/pages/reference/extensions/google-secret-manager.adoc
YN0000: [build:antora  ] [build:antora-perf]     source: https://github.com/apache/camel-quarkus.git (refname: main, start path: docs)
```

I guess it will be fixed by reverting apache/camel-quarkus@a4664f908041ac11874ec78d8ed3c6c618fb23e9?

**Comment by oscerd** [comment]
Not sure. I guess so @jamesnetherton

**Comment by davsclaus** [comment]
Trying a workaround
https://github.com/apache/camel-quarkus/commit/02ef9346febdf6f180a08782dfa87898ab33cb65

**Comment by davsclaus** [comment]
we can try this tomorrow then its also a new day and the website do not have 3 blogs on the same day.

**Comment by davsclaus** [comment]
a new website build
https://ci-builds.apache.org/job/Camel/job/Camel.website/job/main/803/

**Comment by davsclaus** [comment]
Hmm still sees

➤ YN0000: [build:antora  ] [build:antora-perf] [18:57:37.562] ERROR (asciidoctor): target of xref not found: 3.15.x@components::google-secret-manager-component.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     file: docs/modules/ROOT/pages/reference/extensions/google-secret-manager.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     source: https://github.com/apache/camel-quarkus.git (refname: main, start path: docs)
➤ YN0000: [build:antora  ] ERROR: "build:antora-perf" exited with 1.
➤ YN0000: ERROR: "build:antora" exited with 1.

**Comment by davsclaus** [comment]
trying a more ugly fix

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
