### PR TITLE
Added Camel 3.9.x branch

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
@ppalaga @jamesnetherton this should align the 3.9.x branches, but we need some fix on the quarkus side or at quarkus docs side.

**Comment by davsclaus** [comment]
public/camel-quarkus/latest/reference/extensions/core.html
  4:19062  error  For links within camel.apache.org use relative links, found: https://camel.apache.org/camel-quarkus/latest/user-guide/bootstrap.html#_camel_main  camel/relative-links

**Comment by davsclaus** [comment]
New build in progress
https://ci-builds.apache.org/job/Camel/job/Camel.website/view/change-requests/job/PR-557/4/

**Comment by oscerd** [comment]
I think it will fail anyway.

**Comment by oscerd** [comment]
Better but
Found invalid urls in camel-quarkus/latest/reference/extensions/core.html:
	Linked file at path camel-quarkus/latest/reference/extensions/bootstrap.html does not exist!
ERROR: "check:links" exited with 1.

**Comment by davsclaus** [comment]
Trying again with a new fix
https://ci-builds.apache.org/job/Camel/job/Camel.website/view/change-requests/job/PR-557/5/

**Comment by davsclaus** [comment]
The build is now OK


Finished: SUCCESS

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
After this PR is merged and a new website is built, then we should remove the 3.8 branch as that docs should be removed

**Pull request merged**
