### PR TITLE
Added Translate property to category blog aside items

### PR DESCRIPTION
**Pull request by psingh587**
Screenshot from 2020-03-16 16-08-09

I have reopened this PR, as i had not pulled the recent changes made in the original repo earlier and made the PR just like that.

### CODE REVIEW

**Comment by psingh587** [comment]
@zregvart  how do i fix this?

**Comment by oscerd** [comment]
There's nothing you need to fix. Look at the logs of the CI.

[2020-03-16T19:48:08.705Z] ERROR 2020/03/16 19:48:08 Failed to get JSON resource "https://issues.apache.org/jira/rest/api/latest/search?jql=fixVersion=12346526&fields=issuetype,summary": Get https://issues.apache.org/jira/rest/api/latest/search?jql=fixVersion=12346526&fields=issuetype,summary: net/http: TLS handshake timeout

**Comment by zregvart** [comment]
Preview is [here](https://builds.apache.org/job/Camel.website/job/PR-226/Preview/blog/).

**Comment by psingh587** [comment]
> I'm not a fan of such transformations. I guess the question here is do we need this?

Hi @zregvart ,
I guess yes, it looks a little gimmicky to me too. I was actually thinking to make it a not static, at least the buttons and links could possibly have some animations maybe. What else could be done here? Or is it better to leave them as it is?

**Comment by zregvart** [comment]
@psingh587 I'd guess to help with that question we first need to answer the question what's the problem we're addressing with such a change. If it's adding a thing just to add it, I'd avoid adding it.

**Pull request closed without merging**
