### PR TITLE
CAMEL-12470: publish release notes

### PR DESCRIPTION
**Pull request by zregvart**
This adds the data from ASF JIRA to the releases layout and reformats
the releases page.

### CODE REVIEW

**Comment by zregvart** [comment]
Seems that we have an issue accessing JIRA from the build server. There was an JIRA outage earlier today it should [have been resolved](https://status.apache.org/incidents/9ytctmk0wrx8).

**Comment by zregvart** [comment]
Preview is [here](https://builds.apache.org/job/Camel.website/job/PR-164/Preview/index.html), have a look at the [Resolved issues section of 3.1.0](https://builds.apache.org/job/Camel.website/job/PR-164/Preview/releases/release-3.1.0/) for example.

**Comment by zregvart** [comment]
I think I'd like to have a `HUGO_CACHE_DIR` like we have for Yarn and Antora, to be a bit more CI friendly:

https://github.com/apache/camel-website/blob/90b2a5eb0e1a389e0a2578097aa548cf6c8e7c6c/Jenkinsfile#L39-L40

**Comment by oscerd** [comment]
Really nice!

**Comment by oscerd** [comment]
+1

**Comment by oscerd** [comment]
Can we merge this?

**Comment by zregvart** [comment]
I've made tweaks to the release note page, now including the resolved issues as in the preview, and also includes refined Maven dependency information and bit more text to make the release notes a bit more helpful. I'm going through the release blog posts and updating them to reference this release note instead of JIRA. I'll push the changes once the JIRA is [back online](https://status.apache.org/incidents/52krbfwv20h8). No point in building the build will fail.

I also need to add release notes for 3.0-RC releases.

Here is a screenshot of the work:

Screenshot_2020-03-03 Release 3 1 0 - Apache Camel

**Comment by oscerd** [comment]
I love it :-)

**Comment by zregvart** [comment]
Here is the same page as in the screenshot [live on preview](https://builds.apache.org/job/Camel.website/view/change-requests/job/PR-164/Preview/releases/release-3.1.0/).

**Comment by oscerd** [comment]
Perfect!

**Pull request merged**
