### PR TITLE
update irc-room.md

### PR DESCRIPTION
**Pull request by AemieJ**

### CODE REVIEW

**Comment by davsclaus** [comment]
Oh this is some old content - we do not use irc anymore. Maybe we can delete this doc file, and remove it from any index.

**Comment by AemieJ** [comment]
@davsclaus I will do that then if it isn't required anymore.

**Comment by davsclaus** [comment]
Thanks yeah please go ahead and remove it

**Comment by AemieJ** [comment]
And also, didn't find any `index.md` with the context of irc itself.

**Pull request closed without merging**
