### PR TITLE
fix: change CLI names

### PR DESCRIPTION
**Pull request by squakez**
Closes https://github.com/apache/camel-k/issues/4654

### CODE REVIEW

**Comment by zregvart** [comment]
@squakez are you planning on updating the the filenames of older versions in [dist](https://dist.apache.org/repos/dist/dev/camel/camel-k/)?

**Comment by squakez** [comment]
> @squakez are you planning on updating the the filenames of older versions in [dist](https://dist.apache.org/repos/dist/dev/camel/camel-k/)?

Mmm, you're right, this may break the older release pages. Let me see how to manage that. Thanks for the comment.

**Comment by squakez** [comment]
Given the difficulty of making a backward compatible change, I've opted to provide the distribution directory, which format is compatible with all releases.

**Comment by zregvart** [comment]
Also make sure to review the [release distribution policy](https://infra.apache.org/release-distribution.html), from my understanding the source download link must be published to the website. For details on how to maintain releases there is [this page on infra](https://infra.apache.org/release-publishing).

**Pull request merged**
