### PR TITLE
fix: alignment of the documentation page

### PR DESCRIPTION
**Pull request by AemieJ**
The responsiveness for the documentation page wasn't taken into complete account for the smaller screen width. Hence, this PR resolves it.

### BEFORE
bug-layout-responsive

### AFTER
fix-layout-responsive

### CODE REVIEW

**Comment by zregvart** [comment]
The `.yarn/install-state.gz` files should not be part of this commit.

**Comment by aashnajena** [comment]
I think instead of doing this we should remove the extra side padding for smaller screens. If we make the padding under .docs 1% and remove the extra padding for "user manual" and "components" under Camel Core for smaller screens, we should be fine.

**Comment by AemieJ** [comment]
> I think instead of doing this we should remove the extra side padding for smaller screens. If we make the padding under .docs 1% and remove the extra padding for "user manual" and "components" under Camel Core for smaller screens, we should be fine.

Taking your opinion into account, removing padding does create extra spacing however the border-bottom isn't the best bottom as it tends to go out of the frame and I need to make use of the word-break for preventing the link overflowing out of the frame.

**Comment by zregvart** [comment]
This looks good to me, @aashnajena or @delawen any other issues you see?

**Comment by aashnajena** [comment]
LGTM

**Comment by Delawen** [comment]
Good! :+1:

**Comment by zregvart** [comment]
Thanks!

**Pull request merged**
