### PR TITLE
Set CQ 2.7.0 as LTS & add EOL

### PR DESCRIPTION
**Pull request by zbendhiba**

### CODE REVIEW

**Review by aldettinger — APPROVED** [review]
Ok, looks consistent with lts kind of release in camel. And 6 monthes seems to be a good start.

**Review by jamesnetherton — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Review by ppalaga — APPROVED** [review]

**Comment by zbendhiba** [comment]
Hello, I added to this PR the 2.7.1 release

**Comment by davsclaus** [comment]
I wonder if the website wants to build some release notes from gh milestones, but its not set (milestone=) and so it fails
https://api.github.com/repos/apache/camel-quarkus/issues?state=closed&milestone=

**Comment by davsclaus** [comment]
@zbendhiba I think you need to add `milestone: 23` to 2.7.1, and change 23 with the correct number

**Comment by zbendhiba** [comment]
I wonder if the milestone needs to have something in it ?
As we did backports from 2.8, and I can't set the 2 milestones in some GH issues

**Comment by zbendhiba** [comment]
I guess we passed the build phase, and now it fails on checks.

**Comment by davsclaus** [comment]
Yeah @squakez has fixed camel-k, we are waiting for the sql/mongodb fixes for camel project itself. I think @essobedo nows more about these components.

**Comment by davsclaus** [comment]
Re-running jobs as we have fixed website build, so if this is green, then it can be merged

**Comment by zbendhiba** [comment]
The job is all green 🎉
Thanks for the help. I'll merge this one

**Pull request merged**
