### PR TITLE
CAMEL-15118: Reformat the code at build time within the camel website

### PR DESCRIPTION
**Pull request by AemieJ**
* This PR resolves the use of the manual need for formatting to resolve the error while building antora-ui. 

* Apart from that, I rand `yarn format` for the recent changes and have added instructions in **README.md** for using `yarn format`.

### CODE REVIEW

**Comment by djencks** [comment]
This looks good to me.
I don't understand the netlify errors.

**Comment by AemieJ** [comment]
> This looks good to me.
> I don't understand the netlify errors.

Same here, I am unable to interpret where I might be going wrong.

**Comment by zregvart** [comment]
Though changes seem to be only in the format, let's see the build pass before we merge this to make sure. I've re-triggered the Netlify build with cleared cache, that usually helps. Netlify seems to have issues checking out source code from github.

**Comment by lburgazzoli** [comment]
Not sure if the JIRA issue is the right one to use here as CAMEL-14578 was primary targeting auto-formatting the java code of the camel codebase whereas here it is about he website

**Comment by AemieJ** [comment]
> Not sure if the JIRA issue is the right one to use here as CAMEL-14578 was primary targeting auto-formatting the java code of the camel codebase whereas here it is about he website

The JIRA issue clearly doesn't mention the component and based on the description provided by the author for the issue, it clearly fits the problem faced here as well.

**Comment by lburgazzoli** [comment]
> > Not sure if the JIRA issue is the right one to use here as CAMEL-14578 was primary targeting auto-formatting the java code of the camel codebase whereas here it is about he website
> 
> The JIRA issue clearly doesn't mention the component and based on the description provided by the author for the issue, it clearly fits the problem faced here as well.

I know but that issue is already assigned to someone else and now it is a little tricky to know who is working on what so maybe having a subtask assigned to you and with a specific component could have made things a little bit more clear.

**Comment by AemieJ** [comment]
@lburgazzoli I have created a separate issue with the website component and made the changes, is that okay with you now?

**Pull request merged**
