### PR TITLE
CAMEL-17154: Added Dynamic Router EIP Component blog entry.

### PR DESCRIPTION
**Pull request by Steve973**
I added the blog post, but I could not build the website due to many errors, even after installing node and yarn.  I modified links to match those of other blog entries, but I am not using xrefs.  Please have a look, or help me to build this myself, because I do not want to further break the build.

### CODE REVIEW

**Comment by davsclaus** [comment]
You need to adjust the date, look at. the others they dont have time in the date, also make sure it is updated to today, eg 2022-01-14

**Comment by djencks** [comment]
I built it locally and don't see any problems from the time in the date, but the `draft:true` appears to prevent it being published.

**Comment by Steve973** [comment]
Oh, I do remember that I was supposed to remove the draft line, now that
you mention it. Thank you!

**Comment by zregvart** [comment]
@Steve973 there seems to be something wrong with the merge resolution and now we have changes in files that are not related to the blog post. I'll rebase this and hopefully that'll fix it. It will change your own branch, but hopefully for the last time before we merge.

**Comment by Steve973** [comment]
> @Steve973 there seems to be something wrong with the merge resolution and now we have changes in files that are not related to the blog post. I'll rebase this and hopefully that'll fix it. It will change your own branch, but hopefully for the last time before we merge.

@zregvart That reminds me that I fixed the maven build, so those changes in the pom.xml are undoubtedly some unrelated changes.  I woke for work this morning, saw that I had left "draft:true" in the blog post, so I wanted to make that quick change and re-commit.  In the future, I will switch branches when I do any experimenting.

**Comment by zregvart** [comment]
@Steve973 no worries, not much work at all. I'll create a separate PR for the changes in the POM though, I think that'll get the blog post merged faster. I am going to force-push to your branch so just be aware of that.

**Comment by Steve973** [comment]
> @Steve973 no worries, not much work at all. I'll create a separate PR for the changes in the POM though, I think that'll get the blog post merged faster. I am going to force-push to your branch so just be aware of that.

Thank you, again, for your help.  I am a new contributor here, so I am trying to learn how your team does things.  If it comes to a point where you need me to fix whatever I did wrong, just let me know.  I am at work now, where my local time is just before 7am at the time of this comment, so I might not be able to do much for approximately another 7 - 8 hours.

**Comment by Steve973** [comment]
@zregvart let me fix the link that I missed.  One moment...

**Comment by zregvart** [comment]
GitHub workflow seems to have hanged at the very end. Checks look good now. Let's give it a bit and see if we need to retry to get a preview or we can merge and touch-up on after it gets published?

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
