### PR TITLE
Blogpost for VS Code Language Support 0.7.0 release

### PR DESCRIPTION
**Pull request by djelinek**
This is blogpost draft about coming next release of Camel Language Support 0.7.0 vscode extension.

TODO

- update blogpost **date** after extension is released

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by djelinek** [comment]
marked as ready for review

cc @apupier

**Review by apupier — APPROVED** [review]
0..7.0 release is available! https://github.com/KaotoIO/kaoto-ui/issues/1432

**Comment by djelinek** [comment]
Hello @davsclaus @oscerd may I kindly ask you for final review and merge of this blogpost?

- the blogpost date was updated and Camel Language Support 0.7.0 is already out.

Thank you in advance!

**Review by oscerd — APPROVED** [review]

**Comment by djelinek** [comment]
Hello @oscerd , 
I would like to remind myself and if I may
to ask for the merge of this post? it seems the build of page passed. 

Thank you very much in advance.

**Pull request merged**
