### PR TITLE
Fixed table first column font size bold

### PR DESCRIPTION
**Pull request by jyotiattri**
In this PR, I have changed the design of all table that is present on the website. I have seen some tables the first column is bold or some not. I have changed the first column font size bold to make same UI for all the tables.
**Before:**
table-before
**After:**
table-after

### CODE REVIEW

**Comment by djencks** [comment]
I'm not sure about this either.  Perhaps something similar could be done by making the first column into a header column? See https://asciidoctor.org/docs/user-manual/#cols-format.

**Comment by jyotiattri** [comment]
@zregvart, In EIP documentation we can use there main class and make is same as other tables. In the recent changes, I have made changes in EIP documentation.

**Comment by jyotiattri** [comment]
@djencks, Thanks

**Comment by zregvart** [comment]
I don't think this is the right approach, it will break when we change what text is presented in which column. Better approach is the one that @djencks noted, to include such formatting in the source Asciidoc files. Most tables are already generated and what we're working on improving that. It would be much better, in my opinion, to make changes like this in the code generation bits so that these styling options are applied in the source files.

For the components we're using the `indexTable`, e.g. now:

https://github.com/apache/camel/blob/d02f923ecc08e5515a6742485a6c4fe05aac7416/docs/components/modules/ROOT/pages/index.adoc#L18

I think it would be a good idea to expand the `indexTable` so we can include column formatting options. The source for `indexTable` processor is [here](https://gitlab.com/djencks/asciidoctor-antora-indexer), perhaps it would be best to continue this there and improve on this when it's ready to use in Camel.

**Comment by jyotiattri** [comment]
@zregvart, Thanks for the reply. I'll look into [indexTable](https://gitlab.com/djencks/asciidoctor-antora-indexer) and will update you if I can make changes in it.

**Comment by zregvart** [comment]
I think we can close this now.

**Comment by jyotiattri** [comment]
Yes, please

**Pull request closed without merging**
