### PR TITLE
Include the aside block for post but not for blog list

### PR DESCRIPTION
**Pull request by AemieJ**
* I observed that the previous and next arrow direction within the articles were not being displayed in the mobile view. However, when you read a blog article I feel it's very inconvenient to keep moving back to the blog page search through the article and then reading it. Thus, I felt the use of the **previous** and **next** arrows were essential. 

* Hence, I made changes such that the blog list is only hidden for the mobile view however the tag, author and directions of the page is included for each blog post.

### CODE REVIEW

**Comment by AemieJ** [comment]
> I think this issue was caused by #222, perhaps better approach would be to hide the `aside` in `.blog.list` only.

The **aside** block doesn't get displayed in the mobile view. So I thought it was better to provide the user with **previous** and **next** pages for ease. What are you suggesting the better approach is?

**Comment by zregvart** [comment]
> The **aside** block doesn't get displayed in the mobile view. So I thought it was better to provide the user with **previous** and **next** pages for ease. What are you suggesting the better approach is?

Previous and next links of single blog post are part of the `aside` which got hidden in #222 as we wanted to hide the categories menu in the blog post list. We could show `aside` in single blog post but still hide it in blog list.

**Comment by AemieJ** [comment]
> > The **aside** block doesn't get displayed in the mobile view. So I thought it was better to provide the user with **previous** and **next** pages for ease. What are you suggesting the better approach is?
> 
> Previous and next links of single blog post are part of the `aside` which got hidden in #222 as we wanted to hide the categories menu in the blog post list. We could show `aside` in single blog post but still hide it in blog list.

It's a better option to include the summary within the single blog post. However, in my opinion I feel that the user will prefer the next and previous arrow links at the end of the document. I will try to find a better approach and see.

**Comment by zregvart** [comment]
Thanks!

**Pull request merged**
