### PR TITLE
New Releases of VS Code extensions

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by apupier** [comment]
```
Unresolved xrefs (grouped by origin):

repo: https://github.com/apache/camel-k.git | branch: main | component: camel-k | version: latest
  path: docs/modules/ROOT/pages/configuration/configmap-secret.adoc | xref: configuration/logging.adoc

antora: xref validation failed! Found 1 unresolved xref. See previous report for details.
ERROR: "check:xref" exited with 1.
Error: Process completed with exit code 1.
```

I do not see a link between the build error and the PR.

**Comment by apupier** [comment]
this is due to https://github.com/apache/camel-k/commit/db3b1c7b2c685d85b68166605d6e2afa2f5a4752#diff-d9dde282632a1735f238aa7dd03fa98c028e0967e32868b390073d4edc5305cd

**Comment by apupier** [comment]
build to relaunch when https://github.com/apache/camel-k/pull/2261#issuecomment-831288539 is merged

**Comment by orpiske** [comment]
I'm keeping an eye on this one, just in case my recent documentation changes on Camel K broke something else.

**Pull request merged**
