### PR TITLE
wip: new header

### PR DESCRIPTION
**Pull request by zregvart**
This is a work in progress pull request to gather some feedback on the new header design I'm proposing. You can have a look at the code changes, for easier reference I provide before-after screenshots here.

The changes in broad terms are:

 * Increased emphasis of the top level navigation
 * Top level navigation pulled to the left to clear some space for the GitHub/Gitter/Twitter icons, and potentially the search functionality
 * The shadow below the header is more pronounced and deeper encroaching on the secondary navigation in the documentation

**Current homepage:**
Screenshot_2019-07-31 Home page - Apache Camel(1)

**Proposed change:**
Screenshot_2019-07-31 Home page - Apache Camel

**Current documentation page:**
Screenshot_2019-07-31 Java DSL - Apache Camel(1)

**Proposed documentation page:**
Screenshot_2019-07-31 Java DSL - Apache Camel

There's still some work on consolidating this and adding links to the GitHub/Gitter/Twitter icons and making sure that the the new additions are appropriately responsive.

### CODE REVIEW

**Comment by zregvart** [comment]
I've finished with the responsive design (tested it via browser tools), here is how it looks on a 360px wide screen (Galaxy S9 for example):

Screen Shot 2019-07-31 at 17 16 54
Screen Shot 2019-07-31 at 17 16 58

I'm now reasonably satisfied with the outcome.

**Comment by fpapon** [comment]
Nice :+1:

**Comment by oscerd** [comment]
Screenshot_20190731-175411

This is what I'm seeing from mobile

**Comment by zregvart** [comment]
@oscerd that's Android with Chrome browser? I need to fire up a emulator, there's a bit of compatibility issue with using SVGs, I've added a poly-fill that should have helped with that. I'll have a look.

**Comment by zregvart** [comment]
Looks good on Chrome 51 (from 2016) on Android 7 (Ice Cream Sandwich)
Screenshot_1564601884


Screenshot_1564601871

**Comment by bedlaj** [comment]
The header icons are missing on iphone 6 safari. Ataching screen from browserstack. 
camel-safari

Browserstack is offering free licences for opensourse projects, maybe we can get one? https://www.browserstack.com/open-source?ref=pricing

**Comment by zregvart** [comment]
@bedlaj odd, looks good on iPhone 6s (iOS 12.3.1) I'll have a look at browserstack.

**Comment by zregvart** [comment]
Got [some screenshots](https://www.browserstack.com/screenshots/8538d84a55c4e83d2db86fb8aa44c5800c418a07) from browserstack, just from the devices available in the trial.

They look good to me, besides the artefact of having the header show up twice in the screenshots, which I think is an issue with the screenshot taking tool, markup is only present once on the page and I don't see any way for it to show up twice.

**Comment by bedlaj** [comment]
iOS devices are available in trial only for live tests - https://www.browserstack.com/live

**Pull request merged**
