### PR TITLE
chore: add back to top link

### PR DESCRIPTION
**Pull request by zregvart**
Based on #301 this adds "Back to top" link above the footer. @psingh587 can you have a look?

### CODE REVIEW

**Comment by psingh587** [comment]
Screenshot from 2020-04-02 21-06-15

**@zregvart Actually this happens here. The nav-container box gets lifted up here.**

**Comment by psingh587** [comment]
Screenshot from 2020-04-02 21-37-36

**I was thinking to do something like this- Keeping the anchor in the toolbar within same lines as Edit the page for documentation pages**

**Comment by zregvart** [comment]
> Keeping the anchor in the toolbar within same lines as Edit the page for documentation pages.

Yeah, I don't think that's such a good option, it's really hard to find if you're looking for a way back to the top -- the link is at the top.

Also with screen readers, I think I don't know for certain, the back to the top link needs to be at the bottom otherwise folk using screen readers need can't find it.

I'm sure I can find a trick to fix the positioning, let me try to work something out.

**Comment by zregvart** [comment]
@psingh587 I think 6558fccc684f9bf3c8f16862796848a94d4c1658 might fix this, what do you think, there's a preview you can access when the check is done, click on Details next to netlify/camel/deploy-preview when the checks are green?

**Comment by psingh587** [comment]
> @psingh587 I think [6558fcc](https://github.com/apache/camel-website/commit/6558fccc684f9bf3c8f16862796848a94d4c1658) might fix this, what do you think, there's a preview you can access when the check is done, click on Details next to netlify/camel/deploy-preview when the checks are green?

@zregvart This looks good to me. I am closing my PR #301 then.

**Comment by Delawen** [comment]
Preview is on https://deploy-preview-307--camel.netlify.com

**Pull request merged**
