### PR TITLE
chore: add Outreachy update blog post

### PR DESCRIPTION
**Pull request by zregvart**
This blog posts serves to inform Outreachy applicants bout intern selection process and project timeline. If you have some questions that are not answered here or there is uncertainty on what is said here, comments welcome.

### CODE REVIEW

**Comment by Delawen** [comment]
Ok for me, merge!

**Comment by zregvart** [comment]
I'll leave this open for a bit to let some of the applicants chime in if we need to improve the blog post.

**Comment by psingh587** [comment]
Hi @zregvart ,
There's a space in final application which says COMMUNITY SPECIFIC QUESTIONS. 
Here's the description of what it says : 

**Some communities or projects may want you to answer additional questions. Please check with your mentor and community coordinator to see if you need to provide any additional information after you save your final application.**

What are we supposed to do here?

**Comment by zregvart** [comment]
@psingh587 not sure if we have any community specific questions, but you can use the selection criteria we posted here to highlight something

**Pull request merged**
