### PR TITLE
solved search box interferes with menu and logo on smaller resolutions

### PR DESCRIPTION
**Pull request by CSElonewolf**
[CAMEL-14694](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-14694?filter=allopenissues)

Before:-
image 3

After:-
image2

Updated the margin-top ,padding and top of .navbar-search input and #search_results respectively

### CODE REVIEW

**Comment by zregvart** [comment]
Thanks @CSElonewolf, I still miss the logo and the menu we had that's now pushed away by the search box. Do you think you can find a way to have them shown?

I'm not entirely sold on having the search be so prominent on smaller screens, i.e. I think the logo and the menu are more important than the search box.

**Comment by CSElonewolf** [comment]
Then we need to place the serach box have to placed within the hamburger menu in mobile screen. Github does the same(Like visit this same page in mobile to understand what I am trying to say).

**Comment by zregvart** [comment]
@CSElonewolf adding search to the menu is a good option I think.

**Comment by CSElonewolf** [comment]
Ok.Let's proceed.
Btw @zregvart I tried finding the .html file of the complete landing page but couldn't find.As I have an issue to report specifically talking(the div section with "split" class the one with the 20th anniversary logo portion).If you would kind mention me the page in the next following comment it would of massive help :)

**Comment by psingh587** [comment]
Hello,
@zregvart 
In the lines of this PR, I have tried something. Please check and provide the feedback.
#192

**Comment by zregvart** [comment]
@CSElonewolf I think you're looking for the header navigation, which is in [this partial](https://github.com/apache/camel-website/blob/master/layouts/partials/header.html) for Hugo generated content, and again replicated in this [template](https://github.com/apache/camel-website/blob/master/antora-ui-camel/src/partials/header-content.hbs) for the Antora content.

**Comment by CSElonewolf** [comment]
> @CSElonewolf I think you're looking for the header navigation, which is in [this partial](https://github.com/apache/camel-website/blob/master/layouts/partials/header.html) for Hugo generated content, and again replicated in this [template](https://github.com/apache/camel-website/blob/master/antora-ui-camel/src/partials/header-content.hbs) for the Antora content.

Thank you Mr. @zregvart but I know that the html for the navbar section is under the header.html 
But I was asking you about the html of the "20th anniversary logo section". --well this information will be helpful for my next PR.

**Comment by CSElonewolf** [comment]
yyyy

Now we have the logo + searchbar + hamburger menu in mobile version.
@zregvart , @oscerd  and @psingh587 how is it?

**Comment by zregvart** [comment]
Looks good!

Just to make sure we didn't introduce something when merging in #194 I'm going to rebase this on `master` branch and wait for the preview.

**Comment by psingh587** [comment]
> yyyy
> 
> Now we have the logo + searchbar + hamburger menu in mobile version.
> @zregvart , @oscerd and @psingh587 how is it?

@CSElonewolf  you could make the logo a bit smaller to look proportionate with the other items

**Pull request closed without merging**
