### PR TITLE
Add the Camel Quarkus 3.14.0 release blog post

### PR DESCRIPTION
**Pull request by aldettinger**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by apupier** [comment]
unrelated build error, created PR https://github.com/apache/camel/pull/15314

**Comment by aldettinger** [comment]
Ok, many thanks for review all. Let's merge then.

**Comment by apupier** [comment]
I think it would have been better to wait for the fix on camel core merged. So that:
* when merging this one the new build of the website is triggered automatically (you will have to trigger the build manually to have the changes published or hope for another modification in camel-website)
* we can retrigger a build on this PR to check that there are no further errors

**Comment by apupier** [comment]
I think all Camel committers can trigger it https://ci-builds.apache.org/job/Camel/job/Camel.website/job/main/

but there is another error now:
```
[check:links    ] Found invalid urls in components/next/tahu-host-component.html:
[check:links    ] 	Fragment #%3Cem%3Eendpoint_header_CamelTahuMetric%3C/em%3E at components/next/tahu-host-component.html does not exist!
[check:links    ] Found invalid urls in components/next/tahu-edge-component.html:
[check:links    ] 	Fragment #%3Cem%3Eendpoint_header_CamelTahuMetric%3C/em%3E at components/next/tahu-edge-component.html does not exist!
ERROR: "check:links" exited with 1.
```

**Pull request merged**
