### PR TITLE
center elements vertically in navbar

### PR DESCRIPTION
**Pull request by Gunkev**
The original apache website navbar elements are not center aligned vertically in the navigation menu. here is a screenshot
Screenshot from 2020-03-16 18-11-28

so in this PR, I have center the elements. here is the screenshot of the end product
Screenshot from 2020-03-16 18-13-34

### CODE REVIEW

**Comment by Gunkev** [comment]
> This PR is empty.

Please I just fixed check again

**Comment by Gunkev** [comment]
Modified Please check out the PR again

Le lun. 16 mars 2020 à 18:53, Andrea Cosentino <notifications@github.com> a
écrit :

**Comment by oscerd** [comment]
There are two other PRs equal to this one
 And rearrange front page is part of a different work.

**Comment by oscerd** [comment]
This one has been merged https://github.com/apache/camel-website/pull/242

For the other part you were working on we have the other PR you opened. This one can be closed.

**Pull request closed without merging**
