### PR TITLE
Add Camel 3.x migration guide to menu

### PR DESCRIPTION
**Pull request by davsclaus**

### CODE REVIEW

**Comment by davsclaus** [comment]
The PR looks good
https://builds.apache.org/job/Camel.website/job/PR-124/Preview/index.html

**Comment by tadayosi** [comment]
@davsclaus Having two migration guides seems a bit confusing. Maybe renaming 'Camel 3.x migration guide' to 'Camel 3.x upgrade guide' is less confusing?  Just my two cents.

**Comment by davsclaus** [comment]
Ah yeah good point, you are welcome to rename

**Comment by tadayosi** [comment]
@davsclaus thx. I will do.

**Pull request merged**
