### PR TITLE
chore: mirror my latest blog post

### PR DESCRIPTION
**Pull request by nicolaferraro**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by nicolaferraro** [comment]
Should I merge it? The CI keeps failing for other reasons..

**Comment by davsclaus** [comment]
Yeah fine to merge

**Comment by zregvart** [comment]
One thing to be aware of is that the checks haven't run.

**Comment by nicolaferraro** [comment]
> One thing to be aware of is that the checks haven't run.

Ok, let's wait for the issues to be solved first

**Comment by davsclaus** [comment]
Issue resolved, so lets merge

**Pull request merged**
