### PR TITLE
CAMEL-15296:  Create sitemap for Camel website

### PR DESCRIPTION
**Pull request by aashnajena**
This PR adds the first version of sitemap for camel-website. Sitemap can be accessed from the footer. The problem with fetching links programmatically is that links like "misc" and "news" show up, even though they don't have any landing pages. We could choose to hard code all our links instead to avoid such behavior.

### CODE REVIEW

**Comment by AemieJ** [comment]
I like the basic design layout but I just want to clarify that we are going to include more links right? 'cause almost all the links present on the sitemap are there on the footer as well.

**Comment by aashnajena** [comment]
Please suggest which other pages we should put on the sitemap, and I can add those..

**Comment by aashnajena** [comment]
I think we can merge this and improve on it later.

**Comment by AemieJ** [comment]
I believe that we need certain elobaration in site map upto level 1 for the sub projects as well. 'cause if I had to comparatively look at the site map of Apple, it is quite useful as it provides me the direct information neither the navbar nor footer provides. So we could incoperare a more elobrated site map upto max two pages.

However I don't mind this being merged, I can work on it as I have a few additional ideas which I would like to improve on later.

**Comment by zregvart** [comment]
Thanks!

**Pull request merged**
