### PR TITLE
Whats new 4.7 blog. WIP.

### PR DESCRIPTION
**Pull request by davsclaus**

### CODE REVIEW

**Comment by tadayosi** [comment]
@davsclaus Could you briefly mention [CAMEL-20905](https://issues.apache.org/jira/browse/CAMEL-20905) for `camel-djl` at `Miscellaneous`, something like below?
```
The `camel-djl` now supports a more comprehensive set of machine learning applications as follows and is ready for a wider variety of machine learning use cases:

- `cv/image_classification`
- `cv/object_detection`
- `cv/semantic_segmentation`
- `cv/instance_segmentation`
- `cv/pose_estimation`
- `cv/action_recognition`
- `cv/word_recognition`
- `cv/image_generation`
- `cv/image_enhancement`
- `nlp/fill_mask`
- `nlp/question_answer`
- `nlp/text_classification`
- `nlp/sentiment_analysis`
- `nlp/token_classification`
- `nlp/word_embedding`
- `nlp/text_generation`
- `nlp/machine_translation`
- `nlp/multiple_choice`
- `nlp/text_embedding`
- `tabular/linear_regression`
- `tabular/softmax_regression`
- `audio`
- `timeseries/forecasting`
```

**Comment by davsclaus** [comment]
Yeah sure you are welcome to add that

**Comment by tadayosi** [comment]
OK, added. Thanks.

**Review by gzurowski — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Let's try to merge

**Pull request merged**
