### PR TITLE
Fix the broken header menu

### PR DESCRIPTION
**Pull request by aashnajena**
As observed in PR #207 the submenus don't start from below the line. I think there was a PR about shifting the menu text to align with the other elements which caused this change. 
- Instead of the margin, I have added padding. Padding left is 0 so that the drop-downs are aligned with the starting of the text
- Added some padding to the down-arrow button, which seemed too close to the text.   

I think the problem in #207 should also be solved with this.

menu-fixed

### CODE REVIEW

**Comment by aashnajena** [comment]
The drop-down portion starts from below the grey line, so I can make the line beneath the main-menu item white, but it only spans the main-menu-text, not the entire width of the dropdown box.

**Comment by aashnajena** [comment]
Rebased!

**Comment by zregvart** [comment]
This is how it looks currently:

Screenshot_2020-04-01 Outreachy update - Apache Camel

For reference I think what we want is what we [had a month ago](https://web.archive.org/web/20200213140144/http://camel.apache.org/).

Screenshot_2020-04-01 Home - Apache Camel

**Comment by aashnajena** [comment]
I changed it!

**Comment by aashnajena** [comment]
Resolved in PR #306.

**Pull request closed without merging**
