### PR TITLE
Added community articles

### PR DESCRIPTION
**Pull request by fmarchioni**
Added community articles and fixed some broken links

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
> Linked file at path community/articles/www.masterspringboot.com/camel/camel-cheatsheet does not exist!
@fmarchioni  There is a link bug, can you check your code changes and see if you can spot the problem

**Comment by fmarchioni** [comment]
@davsclaus thanks for pointing it out, I've fixed it.
Uh, it seems the GitHub web interface does not allow to squash commits, sorry about the double commit.

**Comment by davsclaus** [comment]
Okay now its another problem in camel-quarkus, but its not you

**Comment by fmarchioni** [comment]
not sure if it's the same, but I had to add "http://" to fix it, otherwise a github link was created rather

**Pull request merged**
