### PR TITLE
Made table style to be stripped and added padding

### PR DESCRIPTION
**Pull request by dzekem**
Added styling to the table by making the table header to have the camel orange background color and made the table to be striped as shown on the screen shot
Screenshot from 2020-03-08 14-12-18

### CODE REVIEW

**Comment by oscerd** [comment]
ok to test

**Comment by zregvart** [comment]
Thanks, it's much better this way! For my taste I would go without table borders as we don't use them in other uses of tables in the documentation.

**Comment by zregvart** [comment]
Perhaps I would mute the colors a bit as well. Here's a quick hack in the CSS inspector:

Screenshot_2020-03-09 Apache Camel 2020 Release Schedule - Apache Camel

That makes it a bit apparent that we also need to center align the `td` content.

**Comment by zregvart** [comment]
And I just noticed, we can't make globally scoped rules in CSS. For example the `table` rule added here applies to all tables on the website. We have slightly different design for tables in the documentation. All rules need to be scoped to the `.blog` CSS class. That is instead of the selector `table` the selector needs to be `.blog table`.

**Pull request merged**
