### PR TITLE
Add blogpost for Language support for Apache Camel - VS Code 0.0.20

### PR DESCRIPTION
**Pull request by apupier**
announcement

Should I need to register the blogpost entry somewhere? or the folders are scanned?

### CODE REVIEW

**Comment by oscerd** [comment]
It should be scanned, lets wait for the preview after the build

**Comment by oscerd** [comment]
ok to test

**Comment by zregvart** [comment]
The HTML validator complains with:
```
17:35:25  public/blog/LanguageSupportTooling-0.0.20/index.html
17:35:25    1:8876  error  Attribute "frameborder" is deprecated on <iframe> element  no-deprecated-attr
```

**Comment by apupier** [comment]
:-( this is the html code provided by youtube itself

Removing the attribute as it seems the easiest to do.

**Comment by davsclaus** [comment]
PR was good, merging

**Pull request merged**
