### PR TITLE
Camel 14781 security page breadcrumps

### PR DESCRIPTION
**Pull request by Siyubu**
While navigating on apache website I saw pages that don't have toolbars breadcrumps such as security page from About/ security. 
Problem resolution:
From the root repository under layouts/ partials/seo/structured I built a breadcrumbs.html partial which get and display the current page user is on.
The partial has been included in root/security/list.html unde main div.
The purpose of making breadcamps.html a partial is making easy the act of displaying breadcrumps on any camel-website page. what is needed is to include it in the targeted page.

### CODE REVIEW

**Comment by Siyubu** [comment]
While navigating on apache website I saw pages that don't have toolbars breadcrumps such as security page from About/ security. 
Problem resolution:
From the root repository under layouts/ partials/seo/structured I built a breadcrumbs.html partial which get and display the current page user is on.
The partial has been included in root/security/list.html unde main div.
The purpose of making breadcamps.html a partial is making easy the act of displaying breadcrumps on any camel-website page. what is needed is to include it in the targeted page.

**Comment by Siyubu** [comment]
> There is yarn.lock and yarn-error.log part of this commit. I don't think is right.

I thought putting them in .gitignore was enough. I am going to delete them

**Comment by Siyubu** [comment]
> There is yarn.lock and yarn-error.log part of this commit. I don't think is right.

I thought putting them in .gitignore was enough. I am going to delete them

**Comment by Siyubu** [comment]
yarn.lock and yarn-error.log removed manually  into the repository

**Comment by Siyubu** [comment]
I removed the .yarn.lock and yarn-error.log, pushed and pull a new request.
However I can't find  my new request at camel website pull requests and all
5 checks are failing. how may I handle .yarn.lock and yarn-error.log, while
even .gitignore is not helping too.
*Solange Iyubu*

Student

Carnegie Mellon University in Africa

Tel: +250 785 562 715

**Comment by Delawen** [comment]
So this PR can be closed because we already have #322 ?

**Pull request closed without merging**
