### PR TITLE
CAMEL-15329: add the community section page

### PR DESCRIPTION
**Pull request by AemieJ**
It is preferred to have the removal of sub-menus from the navbar of the website. This PR deals with the removal of the dropdown items within the community section. 
- Created a community page with minimalist layout.
- Includes the required information and easier for the user to navigate.

Preview for the community page layout is [here](https://deploy-preview-438--camel.netlify.app/community/)

### CODE REVIEW

**Comment by aashnajena** [comment]
I think we can reuse the CSS from the docs page. We could rename the .project class to something more general like .container (to make it semantically appropriate). It will save us from repeating the CSS code.

**Comment by AemieJ** [comment]
I have made the following recent changes - 
- As `docs.css` and `community.css` use the same CSS, I have made the corresponding changes to `docs.css` and `index.md` under **docs** section so the same CSS is being used for both **docs** and **community**.

In addition to this, I tried using `#383284` shade for the SVG icons however they are really dark and don't fit in with the design as compared to the `#e97826` shade.

**Comment by aashnajena** [comment]
@AemieJ front page projects section needs to be fixed

**Comment by AemieJ** [comment]
@aashnajena fixed it. Let me know if you find any further issues.

**Comment by AemieJ** [comment]
@zregvart there is not a requirement to mention the authors of the SVG icons. I have taken it from [flaticon](https://www.flaticon.com/).

**Comment by AemieJ** [comment]
@zregvart the deployment fails 'cause Hugo can't be fetched. I can't find any possible errors in my code as it works perfectly on my local machine.

**Comment by zregvart** [comment]
Thanks!

**Pull request merged**
