### PR TITLE
feat: change frontpage swoosh animation

### PR DESCRIPTION
**Pull request by zregvart**
To freshen up the frontpage a bit, and perhaps to be more representative
of the integration nature of Camel, this changes the swoosh animation to
a "transmission" animation. By using dash pattern of the same SVG paths
we can simulate "messages" traveling from left and right edges of the
screen.

### CODE REVIEW

**Comment by zregvart** [comment]
Preview is [here](https://5ec42c32be4a7300063576f2--camel.netlify.app/).

**Comment by AemieJ** [comment]
> Preview is [here](https://5ec42c32be4a7300063576f2--camel.netlify.app/).

In my opinion, we could make the animation a bit slow and components within an animation spread out 'cause they are really close and timing per frame is too fast. It creates dizziness after a while. It would be more soothing if it were a slower time per frame.

**Comment by aashnajena** [comment]
Looks really good to me!

**Comment by davsclaus** [comment]
The front page has been redesigned so the swoosh animation is no long there, so lets close this PR

**Pull request closed without merging**
