### PR TITLE
Provide Camel K 1.3.0 release apache/camel-k#1867

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
Cc @nicolaferraro @zregvart

**Review by nicolaferraro — APPROVED** [review]

**Comment by nicolaferraro** [comment]
One thing I've noticed is that release notes are not right, see: https://pr-530--camel.netlify.app/releases/k-1.3.0/#resolved

That are the PRs merged on the 1.3.x branch, that will be part of 1.3.1, while the notes for 1.3.0 are missing. Where are they computed from?

**Comment by apupier** [comment]
> That are the PRs merged on the 1.3.x branch, that will be part of 1.3.1, while the notes for 1.3.0 are missing. Where are they computed from?

if I understand well, it is based on the "milestone" field: https://github.com/apache/camel-website/pull/530/files#diff-641c6b7b9f25cf3b42fa87dcfc8e07d7e898e4b9b0b5b3c5e259aecc13ff0b55R10

I incremented the milestone field by 1. I do not know how to find the specific number. it is using this kind of url https://api.github.com/repos/apache/camel-k/issues?state=closed&milestone= (based on a previous local build url that I had when I didn't specified the milestone)

**Comment by apupier** [comment]
found the milestone id!
from this page: https://github.com/apache/camel-k/milestones
https://github.com/apache/camel-k/milestone/11

will update PR

**Pull request merged**
