### PR TITLE
Fixed blog page categories issue

### PR DESCRIPTION
**Pull request by jyotiattri**
Implemented the requested changes from [#213 ](https://github.com/apache/camel-website/pull/213)

### CODE REVIEW

**Comment by jyotiattri** [comment]
Is there any problem with code @zregvart. Please let me know.

**Comment by oscerd** [comment]
I restarted the build.

**Comment by jyotiattri** [comment]
"Can you also squash commits into a single one?" @zregvart send this comment in [#213 ](https://github.com/apache/camel-website/pull/213) that why I squash commit in single PR. Is there anything I have done wrong.

**Comment by oscerd** [comment]
I don't think so, but if this is the squashed one, please close the other PR. Otherwise there is confusion.

**Comment by jyotiattri** [comment]
Closed the PR [#213 ](https://github.com/apache/camel-website/pull/213)

**Comment by jyotiattri** [comment]
Hi, @zregvart 
Please let me know is there something to do in this PR.

**Comment by zregvart** [comment]
The preview is [here](https://builds.apache.org/job/Camel.website/job/PR-222/Preview/blog/).

**Comment by zregvart** [comment]
Thanks!

**Pull request merged**
