### PR TITLE
Improve search results layout

### PR DESCRIPTION
**Pull request by aashnajena**
Currently, the search results look like this :
search-old

The colour scheme, as well as layout, needed updating. I have also added a hover effect for the links. It looks like this now :  
search-new-highlight

Here are few more things I was considering :
1) highlighting the matches word by making it bold/italics/different color
2) adding a "view all matches" tab at the bottom of search_results, to allow user to go to a page with all search results.

Please let me know your suggestions.

### CODE REVIEW

**Comment by aashnajena** [comment]
Added bold highlight for matched substrings (updated screenshot above) and fixed a minor typos. Also can we rename the js files? In all honesty, it took me a lot of time to realise that 05-nav-search.js is for the quick look-ups and algoliasearch.bundle.js is for header search.

**Comment by djencks** [comment]
I strongly recommend NOT renaming the javascript files.  The camel Antora UI is derived from the Antora default UI, and one of the worst parts of the “Antora experience” is updating a UI from updates in the base default UI.  Renaming files such as 05-nav-search.js would make this even harder.

I suspect that it will be desirable to update the camel UI from the default soon, as the default UI has recently been getting some very nice features such as “on this page” TOC in the right sidebar.  I’d wait until Antora 2.3.0 is released though.

**Comment by aashnajena** [comment]
Sure, noted. Should I also revert the renaming of alogliasearch.bundle.js -> algoliasearch.bundle.js? This seemed like a typo to me.

**Comment by djencks** [comment]
that’s fine since it didn’t come from the Antora default UI.  Fewer typos are better :-)

**Comment by Delawen** [comment]
I like the new style, my eyes are happy with it. But it has conflicts with the master branch. Can you rebase and fix those conflicts?

**Comment by aashnajena** [comment]
Rebased.

**Comment by aashnajena** [comment]
Done!

**Comment by zregvart** [comment]
Thanks!

**Pull request merged**
