### PR TITLE
Mobile Menu Enhancement

### PR DESCRIPTION
**Pull request by avgupt**
Fixes: https://issues.apache.org/jira/browse/CAMEL-14695?filter=12348381

### CODE REVIEW

**Comment by avgupt** [comment]
@zregvart Please take a look.

**Comment by zregvart** [comment]
Preview is [here](https://builds.apache.org/job/Camel.website/job/PR-194/Preview/index.html).

Here is how it looks on width of 360:

Screenshot_2020-03-11 Home - Apache Camel

@psingh587 and @CSElonewolf what do you think of this, is it compatible with the approach you're taking? Can we go ahead with this and with your changes?

**Comment by CSElonewolf** [comment]
@zregvart this looks super clean :).
But if we can include the search box now and like @psingh587 did in her PR #192 if now applied it will be a great achievement as per mobile screen navbar standard.
what do you guys have to say @zregvart , @oscerd and @psingh587

**Comment by psingh587** [comment]
> @zregvart this looks super clean :).
> But if we can include the search box now and like @psingh587 did in her PR #192 if now applied it will be a great achievement as per mobile screen navbar standard.
> what do you guys have to say @zregvart , @oscerd and @psingh587
> If this PR #194 gets merged.Then the work on PR #192 can be smoothly done and the main objective of PR #191 will be achieved. :)

I agree with @CSElonewolf  here. I think there's a lot more scope to this one.

**Comment by CSElonewolf** [comment]
Well @psingh587 I am working on it let's see what happens.Hopefully some awesome happens.

**Comment by zregvart** [comment]
Okay so looks like we can merge this and then proceed as suggested in https://github.com/apache/camel-website/pull/194#issuecomment-597775222. Thank you all!

**Comment by CSElonewolf** [comment]
> Okay so looks like we can merge this and then proceed as suggested in [#194 (comment)](https://github.com/apache/camel-website/pull/194#issuecomment-597775222). Thank you all!

Yeah.Visit PR #191 and check the changes made.

yyyy

**Pull request merged**
