### PR TITLE
Added details about our SonarQube instance hosted by ASF Infra

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by zregvart** [comment]
Seems that a Spring Boot starter is missing, perhaps for the new Dynamic Router EIP.

**Comment by davsclaus** [comment]
I think its `camel-springdoc-starter` as its a spring-boot only that does not exists in core camel

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
Ah the local build shows

```
There are 339 spring boot starter json files.

Of these 338 are used in components, dataformats, etc.

Unused spring-boot-starter names

dynamic-router
```

**Comment by davsclaus** [comment]
Its weird as it ends up listed as

```
Non-Spring-Boot Components

Component | Artifact | Support Level | Since | Description
-- | -- | -- | -- | --
Dynamic Router | camel-dynamic-router-starter | Preview | 3.15 | The Dynamic Router component routes exchanges to recipients, and the recipients (and their rules) may change at runtime.
MicroProfile Metrics | camel-microprofile-metrics-starter | Stable | 3.0 | Expose metrics from Camel routes.
Properties | camel-base-starter | Stable | 2.3 | The properties component is used for property placeholders in your Camel application, such as endpoint URIs.

</div>
```

**Comment by davsclaus** [comment]
Okay so it looks like its missing 
```
:base-missing-query: {base-query},attributes=!camel-spring-boot-name
```

but there are no adoc file where it could be, just a copy of the spring boots own json metadata for its auto configuration options

**Comment by davsclaus** [comment]
Okay I may have got it, so there was both something wrong with springdoc and dynamic-router
https://github.com/apache/camel/commit/2ff769be27aeb5553f77135a93051fdad3d6c0ef

**Pull request merged**
