### PR TITLE
CAMEL-13818: design of the blog section

### PR DESCRIPTION
**Pull request by zregvart**
Summary of changes:
 - news section renamed to blog
 - blog section revamped with featured images
 - headings are now bold (previously normal)
 - minification removed from Hugo build (random issues, done by
   htmlminify in gulp anyhow)
 - taxonomy for categories enabled and initial design added

### CODE REVIEW

**Comment by oscerd** [comment]
it looks good to me.

**Comment by zregvart** [comment]
Could be something in the camel-maven-package plugin, mvel templates. I thought I ported over the changes that re-leveled auto generated the headings.

**Comment by zregvart** [comment]
I've done the full build and regenerated the docs, I think I can fix this in a single commit soon.

**Comment by oscerd** [comment]
I already fixed the kubernetes part

**Comment by zregvart** [comment]
I'll just clean up the "Available as of Camel ..." that are duplicated...

**Comment by zregvart** [comment]
Here's [the preview](https://builds.apache.org/job/Camel.website/job/PR-88/Preview/index.html).

**Pull request merged**
