### PR TITLE
Fix button hover transform effect

### PR DESCRIPTION
**Pull request by jyotiattri**
The homepage buttons have a slight issue while hovering over the top of the button. It starts vibrating if you keep the cursor over it.  This PR adds a fix for this issue.

apache-home

Please check this screencast for details:
https://www.dropbox.com/s/s50y0u9f1ymxuld/Home%20-%20Apache%20Camel.webm?dl=0

### CODE REVIEW

**Comment by zregvart** [comment]
Preview is [here](https://deploy-preview-281--camel.netlify.com/)

**Comment by jyotiattri** [comment]
@zregvart, OK Thanks

**Comment by zregvart** [comment]
@jyotiattri are you working on this or can this be closed?

**Comment by jyotiattri** [comment]
@zregvart, No, Please close this.

**Pull request closed without merging**
