### PR TITLE
Improvement upon the navbar-menu

### PR DESCRIPTION
**Pull request by psingh587**
This is regarding the merged PR #194 
  I have tried making some amendments to it 
@zregvart  @oscerd  Please check it.

This is how the navbar-menu covers the whole space on 1023px. What I feel is that it is not neccessary to have it cover the entire window here. 
1023-orginal

this is my version (when width is 1023px)
1023-myversion

and also i think in smaller resolutions it can cover the entire screen so here's my take on it..
Mob-local

### CODE REVIEW

**Comment by psingh587** [comment]
Sir, is this okay.? if not how shall i proceed about this?
@zregvart @oscerd

**Comment by psingh587** [comment]
the second commit does something like this 
WhatsApp Image 2020-03-12 at 05 53 56


  --the color is same as what the navbar items in bigger resolution have, also the dropdown list items have underline hover property .

**Comment by psingh587** [comment]
@zregvart @oscerd  
Sir, How were these changes I made? 
How should I go about improving them if they aren't satisfactory?
Please guide

**Comment by zregvart** [comment]
Thanks!

**Pull request merged**
