### PR TITLE
resolves task 14757 issue 14747 playbook for eip as separate component

### PR DESCRIPTION
**Pull request by djencks**
playbook and front page changes for aggregated eip content, as a separate component

### CODE REVIEW

**Comment by djencks** [comment]
I could rebase, but there's no point unless you actively prefer EIP as a separate component, in which case I will have to come up with a PR to undo the difference between https://github.com/apache/camel/pull/3658 and https://github.com/apache/camel/pull/3658 and https://github.com/apache/camel/pull/3659.  If everyone is OK with EIP as part of components this PR can be closed and discarded.

**Comment by oscerd** [comment]
Sounds good. Just close then

**Comment by oscerd** [comment]
Thanks

**Comment by djencks** [comment]
Decided on eips in components component, so this PR is unnecessary.

**Comment by djencks** [comment]
I thought I'd already closed this....

**Pull request closed without merging**
