### PR TITLE
Automate the process of building the website using Makefile

### PR DESCRIPTION
**Pull request by AemieJ**
To ease the building of the website and automate the process with a single step to build and preview, I believe the use of Makefile is a good solution. In my opinion, any new contributor or current contributor can easily build the projects by using the `make` command by following the instructions I updated for README.

### CODE REVIEW

**Comment by djencks** [comment]
Can't you do this just as well with a gulp file without introducing the use of yet another tool?

**Comment by AemieJ** [comment]
@djencks I will look into that. 👍

**Comment by AemieJ** [comment]
@djencks Yes, there is a library within gulp( **child_process** ) with which it would be possible however for this case ( just building of the website easily ), I thought Makefile would be a better option 'cause it is really easy to maintain as well.

**Comment by zregvart** [comment]
Thanks for understanding @AemieJ, I think simplifying the build is a great idea, and your proposal made me think that we can use Yarn workspaces to make it a bit easier. See https://issues.apache.org/jira/browse/CAMEL-15249 for the idea.

**Comment by AemieJ** [comment]
@zregvart I will give a look at it. It seems a more suitable option for this case.

**Pull request closed without merging**
