### PR TITLE
Fixed issue for text too small for pages

### PR DESCRIPTION
**Pull request by jyotiattri**
This adds a fix for Text too small to read (21 pages) from [Mobile usability issues reported in Google search console](https://issues.apache.org/jira/browse/CAMEL-13800)

cc: @zregvart

### CODE REVIEW

**Comment by jyotiattri** [comment]
Hi, @zregvart 
Please let me know is there something to do in this PR.

**Comment by zregvart** [comment]
@jyotiattri can you take the review into consideration, are you still working on this?

**Comment by jyotiattri** [comment]
Yes, I am working on the suggested changes.

**Comment by zregvart** [comment]
Thanks!

**Pull request merged**
