### PR TITLE
updated the the stroke-opacity and animation delay

### PR DESCRIPTION
**Pull request by CSElonewolf**
[CAMEL-14676](https://issues.apache.org/jira/browse/CAMEL-14676)
Changes were made for making the swoosh design more apparent.

### CODE REVIEW

**Comment by CSElonewolf** [comment]
Thanks @oscerd for taking your time to approve my commit

**Comment by CSElonewolf** [comment]
new issue

I have noticed that the right-side nabvar-item section has does not highlight the visited link like the left-side user manual section does.Therefore I thought of adding a css.
The only extra changes that needs to be done is to add the ".is-current-page" class in the <div> section containing the "is-hoverable" class.

please review the commit nad let me know

@zregvart and @oscerd

**Comment by zregvart** [comment]
Thank you, the swoosh animation does look more apparent now. Here's the [preview](https://builds.apache.org/job/Camel.website/job/PR-171/Preview/index.html).

We like to keep our changes on topic, so I would prefer that the changes in 75798bd535d45e5edaa167d8ed45a5770ac6faa4 are done on a separate pull request if possible.

And with regards to that change the CSS lint is reporting two issues:

```
17:38:30  src/css/header.css
17:38:30   371:1  ✖  Expected empty line before rule        rule-empty-line-before
17:38:30   373:2  ✖  Unexpected whitespace at end of line   no-eol-whitespace
```

You can run the build locally in the `antora-ui-camel` directory by doing `yarn build` there to make sure changes do not introduce lint errors.

**Comment by CSElonewolf** [comment]
@zregvart I will definitely keep that in mind and I will be definitely pull requesting separately.Because being an Outreachy applicant and open source lover.I would love to contribute for the betterment of the site. :)

**Comment by CSElonewolf** [comment]
> Thank you, the swoosh animation does look more apparent now. Here's the [preview](https://builds.apache.org/job/Camel.website/job/PR-171/Preview/index.html).
> 
> We like to keep our changes on topic, so I would prefer that the changes in [75798bd](https://github.com/apache/camel-website/commit/75798bd535d45e5edaa167d8ed45a5770ac6faa4) are done on a separate pull request if possible.
> 
> And with regards to that change the CSS lint is reporting two issues:
> 
> ```
> 17:38:30  src/css/header.css
> 17:38:30   371:1  ✖  Expected empty line before rule        rule-empty-line-before
> 17:38:30   373:2  ✖  Unexpected whitespace at end of line   no-eol-whitespace
> ```
> 
> You can run the build locally in the `antora-ui-camel` directory by doing `yarn build` there to make sure changes do not introduce lint errors.

The preview looks awesome.

**Comment by zregvart** [comment]
@CSElonewolf perhaps you can include just the first commit you made ce577e929d76aa1706b4db85050f91ff836fc4fd by doing a `git reset ce577e929d76aa1706b4db85050f91ff836fc4fd` followed by `git push --force`.

**Comment by CSElonewolf** [comment]
@zregvart Actually I deleted the [75798bd](https://github.com/apache/camel-website/pull/171/commits/75798bd535d45e5edaa167d8ed45a5770ac6faa4)
commit.

**Comment by zregvart** [comment]
@CSElonewolf you deleted the whole file `antora-ui-camel/src/css/header.css` which contains CSS styling we need, not just the changes you made. You can see on the [Files changed](https://github.com/apache/camel-website/pull/171/files) tab that the whole file was deleted.

If you're using GitHub user interface to create pull request then I don't think you can remove commits from the pull request, so it might be easier for you to close this one and create a new pull request with the change you intended.

If you're using the `git` command line then doing `git reset` followed by `git push` as commented above will do that for this pull request.

**Comment by CSElonewolf** [comment]
@zregvart actually the file that contains the css to make changes aare present in `antora-ui-camel/src/css/frontpage.css`.
My very first commit.

**Pull request closed without merging**
