### PR TITLE
chore: new catchphrase for Camel 3 announcement

### PR DESCRIPTION
**Pull request by zregvart**
This replaces the catchphrase "Integration you want" with "Camel 3.0 is
here, what's new" and links the "what's new" to the Camel 3 changes blog
post.

### CODE REVIEW

**Comment by zregvart** [comment]
This is one option to announce Camel 3 on the homepage #121 is another one. Please chime in with your thoughts. I'll paste a link to the preview when it gets built.

**Comment by zregvart** [comment]
Preview is [here](https://builds.apache.org/view/C/view/Apache%20Camel/job/Camel.website/view/change-requests/job/PR-122/Preview/index.html)

**Comment by davsclaus** [comment]
Yay I like this one. As Camel 3 is very breaking news let's go with this.

**Comment by djencks** [comment]
This one has better visual proportions that #121 IMO. The comma looks funny to me, how about 
```
Camel 3.0 is here!
_what's new_
```

or perhaps a semicolon.

**Comment by zregvart** [comment]
I've replaced the comma with an exclamation point and added line break opportunity, preview should be built shortly I'll post the link then.

**Comment by zregvart** [comment]
Sorry, got distracted a bit. Here's the [preview](https://builds.apache.org/job/Camel.website/view/change-requests/job/PR-122/Preview/index.html).

**Pull request merged**
