### PR TITLE
CAMEL-15140: Improve Mobile Main-Menu

### PR DESCRIPTION
**Pull request by aashnajena**
In this PR I have :
- Removed the "About" menu-item from the header, because it now present in the footer
- Changed header.hbs and header.html layout files to remove code for sub-menus
- Removed styling for submenus (.navbar-dropdown class is no longer required)
- Changed the design of the main menu on smaller screens as discussed on the JIRA issue.

Here's how it looks for smaller screens in landscape and portrait mode respectively :

image

image

### CODE REVIEW

**Comment by AemieJ** [comment]
@aashnajena PR #448 deals with those changes along with the desktop version as well.

**Comment by aashnajena** [comment]
Thanks for pointing out, I didn't realise you're working on this issue. Please link it to the JIRA issue so that it's easier to track. Since I've already implemented it now, maybe we can take some implementation bits from here and use them eg. the images, the resizable menu (so that it doesn't go to scroll even if orientation is landscape), the dynamic sizes of menu-items which change with height & width of screen, and having paths of logo-images as part of config.toml, so that they are easy to map, if we want to change the images.

**Comment by zregvart** [comment]
@aashnajena having merged #448, is there something that we miss from this or can this PR be closed?

**Comment by aashnajena** [comment]
This can be closed now

**Pull request closed without merging**
