### PR TITLE
Create a sufficient space between the footer-tools and the page

### PR DESCRIPTION
**Pull request by AemieJ**
* I observed that the space between the end of a paragraph or any text content and the footer details was too less and it gave a cramped-up feeling in smaller screen width. 

* Hence, the changes I proposed resolves that issue and create sufficient space between the footer-related context and the text-content.

### BEFORE 
footer-margin-before

### AFTER
footer-margin-after

### CODE REVIEW

**Comment by aashnajena** [comment]
Hey, can you please check once if the issue exists for all pages? From what I see, this issue only exists for the front page, probably because of improper padding of the `.split` div. For all other pages, the split seems to have sufficient space.

**Comment by AemieJ** [comment]
It exists for all I checked all the blog pages as well.

**Comment by zregvart** [comment]
@AemieJ did you check the Antora built pages?

**Comment by AemieJ** [comment]
> @AemieJ did you check the Antora built pages?

Yes, I checked the **Antora built pages** and a few of them have the footer and text-content too clustered. Thus, making these changes will maintain consistent spacing and not look clustered for any page.

**Comment by zregvart** [comment]
@AemieJ  I'm asking because that negative top trick was needed in #307 to have the component/version selection aligned to the bottom. This is with this pull request:

Screenshot_2020-04-07 Support for Apache Karaf - Apache Camel(1)

**Comment by AemieJ** [comment]
> @AemieJ I'm asking because that negative top trick was needed in #307 to have the component/version selection aligned to the bottom. This is with this pull request:
> 
> Screenshot_2020-04-07 Support for Apache Karaf - Apache Camel(1)

Alright, I will fix that.

**Comment by AemieJ** [comment]
I came to the conclusion that this issue exists for the front page and most of the blog pages itself. Hence, I have made the following changes for the front page and the blogs only.

**Comment by zregvart** [comment]
Thanks!

**Pull request merged**
