### PR TITLE
chore: improve navbar readability

### PR DESCRIPTION
**Pull request by zregvart**
Removes the shadow from the top level navigation and restricts it only to the homepage and makes the navbar text, location in documentation and wide/narrow/edit this page links a bit darker.

### CODE REVIEW

**Comment by zregvart** [comment]
Before:

Screenshot_2019-11-13 ActiveMQ Component - Apache Camel(1)

After:
Screenshot_2019-11-13 ActiveMQ Component - Apache Camel

**Comment by zregvart** [comment]
Even lighter navigation background and a bit darker text:

Before:
Screenshot_2019-11-15 ActiveMQ Component - Apache Camel(1)

After:
Screenshot_2019-11-15 ActiveMQ Component - Apache Camel

**Comment by zregvart** [comment]
Preview is [here](https://builds.apache.org/job/Camel.website/job/PR-109/Preview/index.html).

**Comment by oscerd** [comment]
+1 for me. Thanks @zregvart

**Comment by zregvart** [comment]
I've noticed that now the panels (admonition) and code blocks are not as visibly different as before (they had a darker background). I'll do one more pass at this.

**Comment by zregvart** [comment]
I've made the border slightly darker so it's more prominent now. I've also fiddled with border colors so sneaked in a change of the border on tables. I much prefer the blue over the gray.

The border around the admonition and source that was previously blended with the background:

Screenshot_2019-11-15 ActiveMQ Component - Apache Camel

Table border is now blue:

Screenshot_2019-11-15 ActiveMQ Component - Apache Camel(1)

**Pull request merged**
