### PR TITLE
chore: remove unactive Camel K versions

### PR DESCRIPTION
**Pull request by squakez**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
After this we can maybe also remove some CEQ and Kamelets versions

**Comment by davsclaus** [comment]
And CKC we can remove the very old 0.x releases

**Comment by squakez** [comment]
Yes, we need to remove the Kamelets no longer supported as they are having cross reference to CK.

**Comment by davsclaus** [comment]
We need to remove some old CKC versions too, and it seems CKC is referring to old kamelets

➤ YN0000: [build:antora  ] [build:antora-perf] [11:41:14.226] ERROR (asciidoctor): target of xref not found: 0.6.x@camel-kamelets:ROOT:index.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     file: docs/modules/ROOT/pages/index.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     source: https://github.com/apache/camel-kafka-connector.git (refname: camel-kafka-connector-0.11.x, start path: docs)
➤ YN0000: [build:antora  ] [build:antora-perf] [11:41:14.906] ERROR (asciidoctor): target of xref not found: 0.6.x@camel-kamelets::index.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     file: docs/modules/ROOT/pages/index.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     source: https://github.com/apache/camel-kafka-connector.git (refname: camel-kafka-connector-1.0.x, start path: docs)
➤ YN0000: [build:antora  ] [build:antora-perf] [11:41:14.910] ERROR (asciidoctor): target of xref not found: 0.6.x@camel-kamelets:ROOT:index.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     file: docs/modules/ROOT/pages/index.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     source: https://github.com/apache/camel-kafka-connector.git (refname: camel-kafka-connector-1.0.x, start path: docs)
➤ YN0000: [build:antora  ] [build:antora-perf] [11:41:15.436] ERROR (asciidoctor): target of xref not found: 0.6.x@camel-kamelets:ROOT:index.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     file: docs/modules/ROOT/pages/index.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     source: https://github.com/apache/camel-kafka-connector.git (refname: camel-kafka-connector-3.18.x, start path: docs)
➤ YN0000: [build:antora  ] [build:antora-perf] [11:41:15.975] ERROR (asciidoctor): target of xref not found: 0.6.x@camel-kamelets:ROOT:index.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     file: docs/modules/ROOT/pages/index.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     source: https://github.com/apache/camel-kafka-connector.git (refname: main, start path: docs)

**Comment by davsclaus** [comment]
Okay CKC is EOL by end of this year, so we could also remove it as it depends on kamelets 0.6.x. 

The 3.18.x version of CKC uses kamelets 0.9.x
https://camel.apache.org/camel-kafka-connector/3.18.x/

**Comment by squakez** [comment]
Superseded by #954

**Pull request closed without merging**
