### PR TITLE
blogpost for textual edition of Camel Yaml file

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 JIRA issue: 
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).
 - [x] Make sure you read the [Contributing guidelines in README](https://github.com/apache/camel-website#readme)

### CODE REVIEW

**Review by zregvart — APPROVED** [review]
LGTM

**Comment by davsclaus** [comment]
One issue with a link

> [VS Code Tooling for Apache Camel K]().

LGTM

**Comment by apupier** [comment]
> One issue with a link
> 
> > [VS Code Tooling for Apache Camel K] ().
> 
> LGTM

@davsclaus can you precise where? i cannot find it

**Comment by davsclaus** [comment]
The link is fixed now, it was at CAMEL K MODELINE

**Pull request merged**
