### PR TITLE
CAMEL-15291: create a privacy policy page

### PR DESCRIPTION
**Pull request by AemieJ**
* Creation of the privacy policy page based on the [ASF](https://www.apache.org/foundation/policies/privacy.html) one (excluding the content of Google Analytics). 
* This page is not directly accessible from any link right now but can be accessed under `/privacy-policy`. 
* The privacy policy after the merge will be included within the footer links as discussed in [CAMEL-15185](https://issues.apache.org/jira/browse/CAMEL-15185?focusedCommentId=17137897&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17137897) on Jira based on the new footer design.

The link to the privacy policy for the preview is [here](https://deploy-preview-427--camel.netlify.app/privacy-policy).

### CODE REVIEW

**Comment by aashnajena** [comment]
I think it would be better to have the content in the markdown file (would be easy to edit in future). The contents are simple enough to be rendered using the default layout.

**Comment by aashnajena** [comment]
Privacy policy layout file is same as _default/single.html. If you delete your layout file, Hugo should automatically pick up the layout from _default/single.html

**Comment by AemieJ** [comment]
@aashnajena  Thanks for that! 
@zregvart  made the required changes and works as expected.

**Comment by zregvart** [comment]
Thanks!

**Pull request merged**
