### PR TITLE
CAMEL-13817: Change Getting Started links

### PR DESCRIPTION
**Pull request by omarsmak**
Hey @zregvart can you please take a look at it if what I did makes sense? Thanks

### CODE REVIEW

**Comment by zregvart** [comment]
Perhaps it would make sense to remove the `content/docs/getting-started.md` and add a redirect from `/docs/getting-started/` to `/manual/latest/getting-started.html` in `static/.htaccess`.

**Comment by omarsmak** [comment]
Sure, I have deleted the old file and added the redirection

**Comment by omarsmak** [comment]
@zregvart Jenkins build has failed for some reason, is this a hiccup or there is a specific reason? I can't figure out why it has failed

**Comment by bedlaj** [comment]
It was just timeout during docker stop. Nothing to worry about. A have restarted the job and now it is failing on real check:
`[2019-11-13T23:57:34.330Z] page not found from acknowledgments/index.html to docs/getting-started/index.html`

**Comment by zregvart** [comment]
Yeah, we have a check for broken links, this needs to be updated also:

https://github.com/apache/camel-website/blob/5cf5c827625e41c017682a090ecebdc6fba85ea4/layouts/index.html#L14

**Comment by omarsmak** [comment]
@bedlaj thanks a lot, I forgot that I can now actually restart the builds :).
@zregvart actually this file was also changed by this PR as well
https://github.com/apache/camel-website/blob/4b9c4ff6d5a150911350365423a1d8dabf1f1c7f/layouts/index.html#L14
Weird enough that when I run the same checks locally, I don't get any errors:
```
yarn --non-interactive --frozen-lockfile checks                                                  oalsafi@LT-C02YV0PGLVDR
yarn run v1.19.1
$ run-s check:*
$ antora --generator @antora/xref-validator site.yml
$ link-checker --disable-external --mkdocs --allow-hash-href public

2192 files were scanned in public
9939 local links and 0 parent links and 0 remote links were checked
0 errors and 0 warnings
$ html-validate 'public/*/**/*.html' 'public/!(google)*.html'
✨  Done in 111.47s.
```

**Comment by zregvart** [comment]
@omarsmak did you run the build first (`yarn build)? We trust in the website CI build to catch the broken links.

I misread, @bedlaj was correct its this file:

https://github.com/apache/camel-website/blob/5cf5c827625e41c017682a090ecebdc6fba85ea4/layouts/partials/footer.html#L12

**Comment by omarsmak** [comment]
@zregvart actually I was doing `yarn build` always. Somehow I got the checks to work, I had to delete the generated `public` folder and then re-run `yarn build`, I was under the assumption the generated files will be overwritten whenever I do `yarn build`. Sorry, first time working with yarn :D

**Comment by zregvart** [comment]
One last one (I hope):

https://github.com/apache/camel-website/blob/5cf5c827625e41c017682a090ecebdc6fba85ea4/antora-ui-camel/src/partials/footer-content.hbs#L11

**Comment by zregvart** [comment]
Preview here: https://builds.apache.org/job/Camel.website/job/PR-108/Preview/

**Comment by zregvart** [comment]
Thanks @omarsmak!

**Comment by omarsmak** [comment]
No problem! Happy to help :)

**Pull request merged**
