### PR TITLE
minor CSS updated

### PR DESCRIPTION
**Pull request by shreyaag770**
## Normal Resolution:
pic 1

## Mobile Display (Before):
pic3

## Mobile Display(After):
pic2

### CODE REVIEW

**Comment by shreyaag770** [comment]
It will be really helpful if you could tell the reason for all the checks failed so that I won't repeat it again.

**Comment by zregvart** [comment]
@shreyaag770 we sometimes have this intermittent failures with running the website build/checks, I've restarted the build so let's see if we get lucky on the second try.

**Comment by zregvart** [comment]
@shreyaag770 also, can you explain a bit about the motivations behind the changes you propose, it makes it easier for us to review. For example why remove the text from previous/next links?

**Comment by shreyaag770** [comment]
@zregvart I removed the text from previous/next links to make UI better. I also increased the arrow size to make it more easier for mobile user to navigate between next/previous page.

**Comment by zregvart** [comment]
@shreyaag770 can you explain specifically what makes the UI better when text is not present? I think having the text present makes for a larger touch target on mobile, so easier for the user to click on the link. Can you share your thoughts on this?

**Comment by zregvart** [comment]
The preview is [here](https://builds.apache.org/job/Camel.website/job/PR-193/Preview/blog/LTS-Release-Schedule/).

**Comment by shreyaag770** [comment]
There were few points I had in mind when I did this change -

- The way text was written was not presentable.

- If there are no text and only arrows in normal display then having text in mobile display was not appealing.

- To solve the user click problem I increased the arrow size, so it improves the UI as well as solve the the problem of mobile usability.

**Comment by shreyaag770** [comment]
By mistake instead of sending another PR ,all the other commits have been applied to this PR. Should I send another PR and close this one? 

The changes I want to make was:
I changed dark colors in Swoosh animation with lighter shades to increase the visibility of text.

Before:

s1

After:
s2

**Comment by zregvart** [comment]
@shreyaag770 yes, we try to make our pull request deal with a single topic, so please create a separate pull request for the swoosh change.

**Comment by shreyaag770** [comment]
Alright! @zregvart Thanku :)

**Comment by shreyaag770** [comment]
Should I send this PR again, 'minor CSS updated'?

**Comment by zregvart** [comment]
We haven't seen any new developments in 10 days so I think we can close this @shreyaag770 feel free to reopen when you have further changes.

**Pull request closed without merging**
