### PR TITLE
Revert "CAMEL-15185: Footer design"

### PR DESCRIPTION
**Pull request by oscerd**
Reverts apache/camel-website#428

### CODE REVIEW

**Comment by oscerd** [comment]
Reverting it, because the website build seems to be broken.

**Comment by AemieJ** [comment]
@oscerd when I do `yarn checks` for the footer-design I receive `page not found from components/3.4.x/eips/request-reply.html to community/support` however request-reply.html isn't present anymore within the website and the PR #428 preview works perfectly.

**Comment by oscerd** [comment]
preview build doesn't do what the CI build does there is no checks for link there.

**Comment by zregvart** [comment]
Yes, we don’t run checks on Netlify because running them would use up the free build minutes we have there.

**Comment by zregvart** [comment]
@aemiej remove everything from the public directory and rebuild, we don’t have a way to remove just the deleted pages.

**Comment by AemieJ** [comment]
@zregvart I did that still `yarn checks` failed for `integration.html` under **camel-k** and I observed that it is present in the other PR that has been merged and built as well.

**Pull request merged**
