### PR TITLE
Release Camel Quarkus 2.5.0 announcement

### PR DESCRIPTION
**Pull request by zbendhiba**
- [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 JIRA issue: 
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).
 - [ ] Make sure you read the [Contributing guidelines in README](https://github.com/apache/camel-website#readme)

### CODE REVIEW

**Review by ppalaga — APPROVED** [review]
Looks good, thanks @zbendhiba!

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
We have some problem with the documentation updates in camel-k at the moment. LGTM anyway.

**Review by davsclaus — APPROVED** [review]
Move the date to 25th

**Comment by zbendhiba** [comment]
> Move the date to 25th

Thanks. I've just changed the date

**Review by aldettinger — APPROVED** [review]

**Comment by zbendhiba** [comment]
> We have some problem with the documentation updates in camel-k at the moment. LGTM anyway.

I guess this means the website won't build anyway if we merge this. Am I right ?

**Comment by oscerd** [comment]
I'm running the ci website build again

**Comment by apupier** [comment]
the master is working again. You can rebase the PR to have it passing

**Comment by zbendhiba** [comment]
> the master is working again. You can rebase the PR to have it passing

thanks :crossed_fingers:

**Comment by zbendhiba** [comment]
I've just changed the date of blog post. To make it today.

**Pull request merged**
