### PR TITLE
Improvize the frontpage design

### PR DESCRIPTION
**Pull request by AemieJ**
* I had some issues regarding the arrangement with the text within the **navbar** and in the **header frontpage**.
1.  In the **navbar**, the navbar links were really close to the logo brand, hence I provided a margin between the logo and the **navbar-end**.

### BEFORE 
alignment-before

### AFTER 
alignment

### CODE REVIEW

**Comment by AemieJ** [comment]
Alright, then we can increase the space and leave the text as it is. I will make the changes related to that.

**Comment by zregvart** [comment]
Just noticed that the whole top level navigation doesn't fit on 1024px width, both in the current version and in this PR. It's probably been like that since we added the search box. Not sure if this PR is helping with that though it looks better on wider screens. Not sure how to proceed, seems like we need to rethink the top level navigation.

**Comment by AemieJ** [comment]
> Just noticed that the whole top level navigation doesn't fit on 1024px width, both in the current version and in this PR. It's probably been like that since we added the search box. Not sure if this PR is helping with that though it looks better on wider screens. Not sure how to proceed, seems like we need to rethink the top level navigation.

I can work on that and see if I can resolve that.

**Comment by AemieJ** [comment]
I have additionally done the following changes: 
1. For width <= 1024px, the search box will not appear.
2. For width between 1024px-1230px, the margin between logo and the navbar menu is 1rem. 
3. For default, the margin between the logo and the navbar menu is 2rem.

**Comment by Delawen** [comment]
So for width < 1024px we will not be able to search? I know less than 1024px is not common on computers but it's still like 9% of total web users:

https://www.w3schools.com/browsers/browsers_display.asp

**Comment by AemieJ** [comment]
> So for width < 1024px we will not be able to search? I know less than 1024px is not common on computers but it's still like 9% of total web users:
> 
> https://www.w3schools.com/browsers/browsers_display.asp
> https://gs.statcounter.com/screen-resolution-stats

I will see through this.

**Comment by AemieJ** [comment]
@zregvart  How about for screen width between 1024px and 1175px wi, the search is present below the social icons and the navbar height is increased?

**Comment by zregvart** [comment]
I think this overall improves the design.

There's also a pull request to put the search box in the hamburger menu, so folk with lower widths can still access the search.

In the future I think we need to rethink the number of items in the top level navigation and media breakpoints -- we seem to be adding more and more of them rather than designing for specific screen widths based on data we have. I think this requires bit more effort so best left for the internship where we can devote the time to change the design as we see fit.

**Pull request merged**
