### PR TITLE
Blogpost for VS Code Language Support 0.16.0 release

### PR DESCRIPTION
**Pull request by djelinek**
drafting new blogpost for latest new features of Language Support for Apache Camel (VS Code extension)

@apupier may I ask for feedback before I will mark as ready for review?

### CODE REVIEW

**Review by apupier — CHANGES_REQUESTED** [review]
- I think we need to mention that this blogpost covers changes for several versions, like mention since last blogpost and pointing to it
- there is a compilation error on CI but do not understand what is wrong

**Comment by djelinek** [comment]
> * I think we need to mention that this blogpost covers changes for several versions, like mention since last blogpost and pointing to it
> * there is a compilation error on CI but do not understand what is wrong

I have added notes about changes were made during multiple versions - https://github.com/apache/camel-website/pull/1157/files#diff-f4a57f79b0b099dda181009aee63c65e710fb025a6a77e56a417a060b15981f3R13

also removed some redundant double quotes in header of index.md so hope the build should pass now

**Comment by apupier** [comment]
current failure:

```
[check:links    ] Found invalid urls in blog/2024/03/language-support-release-0.16.0/index.html:
[check:links    ] 	Linked file at path blog/2023/07/multi-release-vscode-extensions/index.md does not exist!
```

**Comment by djelinek** [comment]
> current failure:
> 
> ```
> [check:links    ] Found invalid urls in blog/2024/03/language-support-release-0.16.0/index.html:
> [check:links    ] 	Linked file at path blog/2023/07/multi-release-vscode-extensions/index.md does not exist!
> ```

grrrh.. another attempt.. I have skipped /index.md part which is not in original hyperlink to the page in browser

**Pull request merged**
