### PR TITLE
CAMEL-14682: Upgrade to Yarn Berry

### PR DESCRIPTION
**Pull request by zregvart**
This upgrades to the latest Yarn 2 (Berry). I've opted to the zero
install[1] configuration for added stability, see the linked
documentation on the argumentation and potential drawbacks.

This first commit contains the configuration changes, most notably:
 - upgrading from 1.22.0 to berry
 - changing the xref-checker URL to supported syntax
 - switching from hugo-cli to hugo-extended, as the former tries to
   write to the module directory and the later uses bin-wrapper as an
   install time build step. Yarn would fail on former but later has no
   such issues
 - wildcards used in scripts are not supported so scripts need to be
   explicitly stated
 - Jenkins and Netlify builds no longer require `yarn install` due to
   the usage of zero install

Next commit will contain the cache used by the zero install.

[1] yarnpkg.com/features/zero-installs

Fore reviewers 096265a contains the actual changes, cc1561a contains the changes needed for zero install no need to go through those.

### CODE REVIEW

**Comment by AemieJ** [comment]
@zregvart I worked on this, with yarn berry upgrade, I can easily make use of workspaces compared to the previous version.

**Comment by zregvart** [comment]
> @zregvart I worked on this, with yarn berry upgrade, I can easily make use of workspaces compared to the previous version.

Thanks for checking @AemieJ, now we have to get the CI checks to pass, I'm not sure if the newer version of the xref checker is to blame for the failure [on Jenkins](https://builds.apache.org/job/Camel.website/job/issue%252FCAMEL-14682/3/console); the issue [on Netlify](https://app.netlify.com/sites/camel/deploys/5ef97947f963820008d62ff5) is even more perplexing.

**Comment by zregvart** [comment]
I'm seeing unresolved xrefs:

```
Unresolved xrefs (grouped by origin):           	                                                       	                             

repo: https://github.com/apache/camel.git | branch: camel-2.x | component: components | version: 2.x
  path: docs/components/modules/dataformats/pages/index.adoc | xref: 2.x@components:dataformats:nav.adoc
  path: docs/components/modules/languages/pages/index.adoc | xref: 2.x@components:languages:nav.adoc
  path: docs/components/modules/others/pages/index.adoc | xref: 2.x@components:others:nav.adoc
  path: docs/components/modules/ROOT/pages/index.adoc | xref: 2.x@components:ROOT:nav.adoc

repo: https://github.com/apache/camel.git | branch: camel-3.4.x | component: components | version: 3.4.x
  path: docs/components/modules/dataformats/pages/index.adoc | xref: 3.4.x@components:dataformats:nav.adoc
  path: docs/components/modules/languages/pages/index.adoc | xref: 3.4.x@components:languages:nav.adoc
  path: docs/components/modules/others/pages/index.adoc | xref: 3.4.x@components:others:nav.adoc
  path: docs/components/modules/ROOT/pages/index.adoc | xref: 3.4.x@components:ROOT:nav.adoc

repo: https://github.com/apache/camel.git | branch: master | component: components | version: latest
  path: docs/components/modules/dataformats/pages/index.adoc | xref: latest@components:dataformats:nav.adoc
  path: docs/components/modules/languages/pages/index.adoc | xref: latest@components:languages:nav.adoc
  path: docs/components/modules/others/pages/index.adoc | xref: latest@components:others:nav.adoc
  path: docs/components/modules/ROOT/pages/index.adoc | xref: latest@components:ROOT:nav.adoc

antora: xref validation failed! Found 12 unresolved xrefs. See previous report for details.
```

**Comment by djencks** [comment]
This is due to a recent change in the xref-validator, where nav files are adopted by the page family.  See https://gitlab.com/antora/xref-validator/-/issues/9 <https://gitlab.com/antora/xref-validator/-/issues/9>

David Jencks

**Comment by zregvart** [comment]
I think I'll force the older version of xref-validator we use on main branch here and update when a fix is ready (either in the asciidoctor-antora-indexer or in the xref-validator).

**Comment by zregvart** [comment]
Seems that I've missed something in the theme build, this is reported [on CI](https://ci-builds.apache.org/job/Camel/job/Camel.website/job/PR-417/30/console):
```
➤ YN0000: [08:42:30] The following tasks did not complete: bundle, <series>, build
➤ YN0000: [08:42:30] Did you forget to signal async completion?
```

I'll work on getting that fixed before I merge this.

**Comment by zregvart** [comment]
Unplugging highlight.js seems to have helped with this. There is still the issue with Netlify preview which I think can be solved by using a newer Yarn version there. The error is:

```
1:43:09 PM: yarn install v1.17.0
1:43:09 PM: error Workspaces can only be enabled in private projects.
1:43:09 PM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
1:43:09 PM: Error during Yarn install
```

**Comment by zregvart** [comment]
Managed to get Netlify to work by forcing version Yarn version 1.22.5. Now some checks fail with:

```
page not found from misc/index.html to misc/%22/privacy-policy%22
page not found from blog/2020/10/ApacheCon-at-Home-videos/index.html to blog/2020/10/ApacheCon-at-Home-videos/Pupier_Aur%C3%A9lien_How_to_contribute_textual_tooling_for_Apache_Camel_in_several_IDEs.pdf
```

Need to investigate that.

**Comment by djencks** [comment]
It's unnecessary to revert the xref validator version, we can change the filter in the indexTable macro. Issue and PRs on its way.

**Comment by zregvart** [comment]
@djencks awesome, thanks!

**Comment by zregvart** [comment]
Seems that versions of html-validate and link-checker were upgraded (I didn't really check). And that causes [validation issues on CI](https://ci-builds.apache.org/job/Camel/job/Camel.website/job/PR-417/40/consoleFull). Latest of which is with the HTML validation. I'll go ahead and fix those on this PR as well.

**Comment by zregvart** [comment]
This passes all checks now. I'm going to merge it.

**Pull request merged**
